/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarRunsRouteImport } from './../routes/_sidebar/runs'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarDataRouteImport } from './../routes/_sidebar/data'
import { Route as SidebarDashboardRouteImport } from './../routes/_sidebar/dashboard'
import { Route as SidebarConfigsRouteImport } from './../routes/_sidebar/configs'
import { Route as SidebarRunsNewRouteImport } from './../routes/_sidebar/runs_.new'
import { Route as SidebarRunsRunIdRouteImport } from './../routes/_sidebar/runs_.$runId'
import { Route as SidebarConfigsNewRouteImport } from './../routes/_sidebar/configs_.new'
import { Route as SidebarConfigsConfigIdRouteImport } from './../routes/_sidebar/configs_.$configId'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRunsRoute = SidebarRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDataRoute = SidebarDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDashboardRoute = SidebarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarConfigsRoute = SidebarConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRunsNewRoute = SidebarRunsNewRouteImport.update({
  id: '/runs_/new',
  path: '/runs/new',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRunsRunIdRoute = SidebarRunsRunIdRouteImport.update({
  id: '/runs_/$runId',
  path: '/runs/$runId',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarConfigsNewRoute = SidebarConfigsNewRouteImport.update({
  id: '/configs_/new',
  path: '/configs/new',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarConfigsConfigIdRoute = SidebarConfigsConfigIdRouteImport.update({
  id: '/configs_/$configId',
  path: '/configs/$configId',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configs': typeof SidebarConfigsRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/data': typeof SidebarDataRoute
  '/profile': typeof SidebarProfileRoute
  '/runs': typeof SidebarRunsRoute
  '/configs/$configId': typeof SidebarConfigsConfigIdRoute
  '/configs/new': typeof SidebarConfigsNewRoute
  '/runs/$runId': typeof SidebarRunsRunIdRoute
  '/runs/new': typeof SidebarRunsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configs': typeof SidebarConfigsRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/data': typeof SidebarDataRoute
  '/profile': typeof SidebarProfileRoute
  '/runs': typeof SidebarRunsRoute
  '/configs/$configId': typeof SidebarConfigsConfigIdRoute
  '/configs/new': typeof SidebarConfigsNewRoute
  '/runs/$runId': typeof SidebarRunsRunIdRoute
  '/runs/new': typeof SidebarRunsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/configs': typeof SidebarConfigsRoute
  '/_sidebar/dashboard': typeof SidebarDashboardRoute
  '/_sidebar/data': typeof SidebarDataRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/runs': typeof SidebarRunsRoute
  '/_sidebar/configs_/$configId': typeof SidebarConfigsConfigIdRoute
  '/_sidebar/configs_/new': typeof SidebarConfigsNewRoute
  '/_sidebar/runs_/$runId': typeof SidebarRunsRunIdRoute
  '/_sidebar/runs_/new': typeof SidebarRunsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configs'
    | '/dashboard'
    | '/data'
    | '/profile'
    | '/runs'
    | '/configs/$configId'
    | '/configs/new'
    | '/runs/$runId'
    | '/runs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configs'
    | '/dashboard'
    | '/data'
    | '/profile'
    | '/runs'
    | '/configs/$configId'
    | '/configs/new'
    | '/runs/$runId'
    | '/runs/new'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/configs'
    | '/_sidebar/dashboard'
    | '/_sidebar/data'
    | '/_sidebar/profile'
    | '/_sidebar/runs'
    | '/_sidebar/configs_/$configId'
    | '/_sidebar/configs_/new'
    | '/_sidebar/runs_/$runId'
    | '/_sidebar/runs_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/runs': {
      id: '/_sidebar/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof SidebarRunsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/data': {
      id: '/_sidebar/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof SidebarDataRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dashboard': {
      id: '/_sidebar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SidebarDashboardRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/configs': {
      id: '/_sidebar/configs'
      path: '/configs'
      fullPath: '/configs'
      preLoaderRoute: typeof SidebarConfigsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/runs_/new': {
      id: '/_sidebar/runs_/new'
      path: '/runs/new'
      fullPath: '/runs/new'
      preLoaderRoute: typeof SidebarRunsNewRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/runs_/$runId': {
      id: '/_sidebar/runs_/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof SidebarRunsRunIdRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/configs_/new': {
      id: '/_sidebar/configs_/new'
      path: '/configs/new'
      fullPath: '/configs/new'
      preLoaderRoute: typeof SidebarConfigsNewRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/configs_/$configId': {
      id: '/_sidebar/configs_/$configId'
      path: '/configs/$configId'
      fullPath: '/configs/$configId'
      preLoaderRoute: typeof SidebarConfigsConfigIdRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarConfigsRoute: typeof SidebarConfigsRoute
  SidebarDashboardRoute: typeof SidebarDashboardRoute
  SidebarDataRoute: typeof SidebarDataRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarRunsRoute: typeof SidebarRunsRoute
  SidebarConfigsConfigIdRoute: typeof SidebarConfigsConfigIdRoute
  SidebarConfigsNewRoute: typeof SidebarConfigsNewRoute
  SidebarRunsRunIdRoute: typeof SidebarRunsRunIdRoute
  SidebarRunsNewRoute: typeof SidebarRunsNewRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarConfigsRoute: SidebarConfigsRoute,
  SidebarDashboardRoute: SidebarDashboardRoute,
  SidebarDataRoute: SidebarDataRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarRunsRoute: SidebarRunsRoute,
  SidebarConfigsConfigIdRoute: SidebarConfigsConfigIdRoute,
  SidebarConfigsNewRoute: SidebarConfigsNewRoute,
  SidebarRunsRunIdRoute: SidebarRunsRunIdRoute,
  SidebarRunsNewRoute: SidebarRunsNewRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
